### PR TITLE
Added BrickPi Powersupply

### PR DESCRIPTION
**Pull request by antonvh**
Is this helpful?

### CODE REVIEW

**Comment by dlech** [comment]
It would be better to write a kernel driver so that this can be used by any programming language, not just python. See ev3dev/ev3dev#413.

This code is very helpful as a reference to do that.

**Comment by dlech** [comment]
I have added a kernel driver partly based on this. I did the math and got 0.017725 which is close to your empirical results. Enabling the driver causes my Pi to crash since there is nothing there (actually more of an infinite loop than a crash) so you will have to test it out after the next kernel release.

**Comment by rhempel** [comment]
I think we're going to skip this PR based on having a kernel driver to support it, yes?

@dlech - we get attributes for voltage and current with your driver?

**Comment by dlech** [comment]
See <https://github.com/ev3dev/ev3dev/issues/412#issuecomment-154242776>. PiStorms is voltage only.

**Comment by dlech** [comment]
And yes, we have an (semi-untested) kernel driver.

**Comment by antonvh** [comment]
Will do! Thanks for adding this!

**Comment by rhempel** [comment]
I will close this PR - when you have code that works with the new kernel driver, open a new PR please.

**Pull request closed without merging**
