### PR TITLE
Module to package

### PR DESCRIPTION
**Pull request by ddemidov**
This pulls in some work of @EricPobot and some of my changes as well.

1. The single file approach is replaced by package again. There is `ev3dev/core.py` that has most of the functionality, and there are `ev3dev/ev3.py` and `ev3dev/brickpi.py` that has platform-specific code. `ev3dev/__init__.py` tries to guess the current platform and imports appropriate file. From the user standpoint nothing has changed: `import * from ev3dev` still works.
2. `Led` class is split into `Led` and `Leds`. `Led` is platform-agnostic class that works with single led. `Leds` is platform-specific stateless class that contains `Led` instances (such as `red_left`, `red_right` for EV3) and color functions (I actually like the chage!). Each platform-specific file defines its own version of `Leds`.
3. I've introduced platform-specific constants (`OUTPUT_X`, `INPUT_X`) into each of the platform-specific files.
4. `Button` class is split into platform-agnostic `ButtonEVIO` and platform-specific `Button`. The former stays in `core.py`.
5. I've introduced `ev3dev/version.py` that is generated by `setup.py` from `git_version.py` and `spec_version.py` (hence it is not part of git repo). It allows to determine package version at runtime:
```py
>>> ev3dev.__version__
'0.4.1.post7 (spec: 0.9.3-pre-r2, kernel: v3.16.7-ckt16-7-ev3dev-ev3)'
```

This PR is accompanied by https://github.com/rhempel/ev3dev-lang/pull/4

### CODE REVIEW

**Comment by ddemidov** [comment]
Travis says its not good, I am looking at it.

**Comment by ddemidov** [comment]
Travis is happy with 933136c. The problem was that version.py was not there after fresh clone. This should not happen to users when they installed the package from pypi or with `apt-get`.

**Comment by rhempel** [comment]
My instincts told me that eventually we'd move to having the platform specific things in separate files - thanks @EricPobot and @ddemidov for making the changes!

**Comment by ddemidov** [comment]
@ensonic, this breaks the Leds API. Basically, you need to use `Leds` instead of `Led` now.

**Comment by ddemidov** [comment]
May be I should have added @EricPobot to the [list of authors](https://github.com/rhempel/ev3dev-lang-python/blob/master/setup.py#L12), but that line may become quite long at this pace. I would replace it with 'Ralph Hempel et al' (and may be a link to [contributors](https://github.com/rhempel/ev3dev-lang-python/graphs/contributors) page)

**Comment by rhempel** [comment]
It's getting a bit long, I agree. How does everyone feel about leaving me as author/maintainer, but others get credit and email address in `ev3dev.py`?

**Comment by ericpascual** [comment]
This is fine for me. No problem.

**Comment by rhempel** [comment]
In that case - what is @EricPobot's preferred email address?

Note to all, please indicate if you would rather NOT have your email address in `ev3dev.py`

**Comment by ddemidov** [comment]
I am ok with having my email address on the list. It's on my github
profile.

On Sun, Nov 1, 2015, 23:03 Ralph Hempel <notifications@github.com> wrote:

> In that case - what is @EricPobot <https://github.com/EricPobot>'s
> preferred email address?
>
> Note to all, please indicate if you would rather NOT have your email
> address in ev3dev.py
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rhempel/ev3dev-lang-python/pull/46#issuecomment-152858887>
> .
>
-- 

Cheers,
Denis

**Comment by ericpascual** [comment]
You can use eric@pobot.org. This is the one I use for the activities related to my robotics association, but is forwarded to my personnal one.
I'm sorry about the confusion which can have been created by my posting  with my professional GitHub identity (i.e. ericpascual).

**Comment by rhempel** [comment]
So you want credit as Eric Pascual :-)

**Comment by ericpascual** [comment]
Since this is my name IRL, it seems the most appropriate ;)

**Comment by ensonic** [comment]
Re leds.: which version will have that change? I'll ignore 0.4.0 then. Also 0.4.0 still misses the port constants (INPUT_1, ...). So it needs another cycle anyway.

**Comment by ddemidov** [comment]
I think this is goind be in 0.4.1. Re constants: this PR has those: https://github.com/rhempel/ev3dev-lang-python/pull/46/files#diff-2d404f179d8fbc68b0ce868c5ac0bd3dR32

**Comment by rhempel** [comment]
I'm working out packaging with @dlech - I'll pull in the constants for the next spin, and since Leds is a breaking change it will be 0.5.0

**Comment by ddemidov** [comment]
Also, I've missed `INPUT_AUTO` and `OUTPUT_AUTO`. I'll make another PR today.

**Comment by rhempel** [comment]
OK, thks - when I receive that I'll merge, bump the version to 0.5.0, push that to pypi, and update the `ev3dev-lang` master repo so that we can do a package build for @ensonic.

@dlech, do you have a method of automating package builds when a new tag gets pushed?

**Comment by dlech** [comment]
Not at the moment.

**Pull request merged**
