### PR TITLE
Switch to decentralized model

### PR DESCRIPTION
**Pull request by ddemidov**
See ev3dev/ev3dev-lang#142

This creates a submodule pointing to decentralized branch of ev3dev/ev3dev-lang, and adds the required `autogen-config.json` file. When this is merged, autogen may be executed as `./ev3dev/exec-autogen.js`.

Also, I am not sure which branch to create pull requests against now. It looks like develop suffered from recent merge disasters. Should it be just hard reset to master?

### CODE REVIEW

**Comment by rhempel** [comment]
Thanks for doing this - I was ready to start work on this for my New Years first project. yes `master` is where I am currently doing merges, but I think I may want instead to start using a more GitHub friendly workflow that uses `master` for actual tagged releases, `develop` for current merging until the next release, and then small feature branches.
Leave the PR against `master` for now - I'll reset `develop` hard to `master` this evening. There's nothing in `develop` that is historically significant except as a lesson in `git` antipatterns.

**Comment by rhempel** [comment]
Thanks!

**Comment by rhempel** [comment]
So after merging this commit, the script is actually at `./ev3dev-lang/exec-autogen.js` - not a big deal.

**Comment by ddemidov** [comment]
Yes, sorry about the misleading typo :)

**Comment by rhempel** [comment]
So far my New Year's resolution has held up - I have not completely clobbered my repo or the history.

**Pull request merged**
