### PR TITLE
Adding auto-drive demo

### PR DESCRIPTION
**Pull request by ddemidov**
Ref #47

### CODE REVIEW

**Comment by ddemidov** [comment]
The demo depends on #76.

**Comment by rhempel** [comment]
Thanks for adding this, what I'll do is post about it to the ev3dev.org site - there's not much going on there right now.

**Comment by ddemidov** [comment]
There is a slight issue I had with the new bindings while implementing this. The boostc version stopped the motors in [their destructors](https://github.com/ddemidov/ev3dev-lang-python/blob/master/ev3dev/__init__.py#L123-L140), and pure python version does not. When something goes wrong in the middle of the script, motors keep rotating, and there is no easy way to stop the motors. May be we should reintroduce the boostc behavior?

**Comment by ensonic** [comment]
+1 I'll do this on the code generated by open-roberta too.

**Comment by rhempel** [comment]
Good idea - destructors should reset the peripheral - this may apply for sensors as well...

**Comment by ddemidov** [comment]
How do you reset a sensor?

**Comment by ensonic** [comment]
Maybe @rhempel meant to restore e.g. the mode.

**Comment by ddemidov** [comment]
But then we either need a concept of default mode for each sensor type, or to remember the state the sensor had at construction time.

**Comment by rhempel** [comment]
I just mean to consider resetting the sensor. For example the NXT light sensor allowed to use the LED as a multi colored light. The destructor should turn the light off. I see the motor destructor PR is done - leave the sensors for later - it won't break anything :-)

**Pull request merged**
