### PR TITLE
Moving ev3dev.py out of ev3dev folder

### PR DESCRIPTION
**Pull request by ddemidov**
This makes the module flat-organized (see #10).
This also adds a `setup.py` file so that the module may be installed with easy_install or uploaded to pypi.

The package may be installed system-wide with
```
sudo python setup.py install
```
The name `python-ev3dev` is currently occupied on PyPI by boostc version of the python bindings, but I can delete or rename the package when we decide we are ready to completely replace it.

### CODE REVIEW

**Comment by ddemidov** [comment]
@rhempel, if you decide to merge it, the `autogen/autogen-list.json` in the main repo would need to be updated as well.

**Comment by rhempel** [comment]
Can we have multiple authors in the author line?
I have fixed the `autogen-list.json` in my branch - it takes advantage of the ability to locate the templates with the specific language binding.

**Comment by rhempel** [comment]
Are we about ready to push this into the official `ev3dev-lang` branch?

**Comment by ddemidov** [comment]
> Can we have multiple authors in the author line?

I think so. This is just a text field.

> Are we about ready to push this into the official ev3dev-lang branch?

This is not yet a direct replacement to boostc version, but that is still available in my repository. I think we can do this and let people start complaining.

**Comment by rhempel** [comment]
I prefer to think of it as "helpful suggestions" :-) OK, I'll get around to merging with the main branch of `ev3dev-lang` later this morning.
Thanks for all of your help on this!

**Pull request merged**
