### PR TITLE
Also flush on read() to not return cached data.

### PR DESCRIPTION
**Pull request by ensonic**
Fixes issue #67

### CODE REVIEW

**Comment by ddemidov** [comment]
Did you also try to open files without buffering and get read of f.flush(), as @dlech [suggested](https://github.com/rhempel/ev3dev-lang-python/issues/67#issuecomment-154111940)?

**Comment by ddemidov** [comment]
Sorry, you did exactly that.

**Comment by rhempel** [comment]
Thanks!

**Comment by ddemidov** [comment]
This breakes python3 compatibility. The following error is raised:
```
  File "./tests/../ev3dev/core.py", line 61, in file_handle
    f = open(path, mode, 0)
ValueError: can't have unbuffered text I/O
```
We probably don't care about python3 compatibility, but its worth mentioning.

**Comment by rhempel** [comment]
Can we fix this by opening in `b`inary mode? I know attributes are text only, but it never really hurts to open in binary mode.

**Comment by ddemidov** [comment]
I tried just replacing moded with binary versions, and it did not work. The error is:
```
Traceback (most recent call last):
  File "./tests/api_tests.py", line 18, in test_device
    d = ev3dev.Device('tacho-motor', 'motor*', driver_name='lego-ev3-m-motor')
  File "./tests/../ev3dev/core.py", line 136, in __init__
    if all([self._matches(k, kwargs[k]) for k in kwargs]):
  File "./tests/../ev3dev/core.py", line 136, in <listcomp>
    if all([self._matches(k, kwargs[k]) for k in kwargs]):
  File "./tests/../ev3dev/core.py", line 159, in _matches
    return value.find(pattern) >= 0
TypeError: a bytes-like object is required, not 'str'
```
I guess we can fix this by explicitly converting strings to bytes and the other way around where appropriate, but I am not sure is this is the best way to go.

**Comment by ensonic** [comment]
Yep, I think we need to do the conversion explicitly. I'll give it a try and send a new PR.

**Pull request merged**
