### PR TITLE
Update changelog for v0.8.0

### PR DESCRIPTION
**Pull request by WasabiFan**
Now that we've added the fonts module, I think we should publish a release to get it out there.

I didn't add the release attribution yet; whenever we actually do this release we can add the attribution.

Also, at some point I think we should align with semver and release a v1.0. Honestly, this seems like a reasonable time to do it. Currently this PR just increments the minor version though.

### CODE REVIEW

**Comment by dwalton76** [comment]
0.8.0 or 0.7.1? Not sure if we have any defined criteria for when we do a major version bump

**Comment by WasabiFan** [comment]
Yeah, that's why I'd like to align with semver at some point... for now, my thinking was essentially that the breaking change on the `NXTMotor` class warranted something more than a patch increment. But it's arbitrary either way.

**Comment by WasabiFan** [comment]
Haha sorry that I hadn't made these changes yet; looks like you did it for me. What name do we want at the bottom? Or do we wait until someone actually builds the release?

**Comment by ddemidov** [comment]
I can try to build the package this weekend (while I still remember how to do this from 0.7.0). I'll put my name then with the rest of the changes required for packaging. This may be merged now.

**Pull request merged**
