### PR TITLE
Switch to group-based interface in Leds

### PR DESCRIPTION
**Pull request by ddemidov**
This is based on discussion at https://github.com/rhempel/ev3dev-lang-python/issues/37#issuecomment-153442761.

This introduces concepts of led groups (see also ev3dev/ev3dev#412) and colors into `Leds` class. The led groups may be operated as in:
```py
# Set group color:
Leds.set_color(Leds.LEFT, Leds.AMBER)
Leds.set_color(Leds.RIGHT, (1.0, 0.75))

# Batch set arbitrary led properties in group:
Leds.set(Leds.LEFT, trigger='timer', brightness_pct=0.5)
```

I hope this is close to what @EricPobot had in mind.

This is accompanied by rhempel/ev3dev-lang@28361dad5e4f33749ee76634eeedfc1b972b6507

### CODE REVIEW

**Comment by ddemidov** [comment]
Also, I hope @ensonic is ok with this change.

**Comment by ddemidov** [comment]
rhempel/ev3dev-lang#5, if/when merged into ev3dev/ev3dev-lang, will break js and C++ bindings, so pinging @WasabiFan as well.

**Comment by rhempel** [comment]
Welcome to the world of hair splitting when it comes to bicoloured LED control. I can give one good reason for retaining individual control, and that is to multiplex more visual information on one LED - ie set one background color for system state, but still allow flashing for disk access. Maybe that's in the realm of overthinking it..

**Comment by ddemidov** [comment]
`Leds` class exposes all the leds present in the system individually as well as in groups. I think that should be enough for any use case.

**Pull request merged**
