### PR TITLE
Update changelog for 0.7.0 release

### PR DESCRIPTION
**Pull request by WasabiFan**
Updated version of #211 with some added items and its own entry. I decided to put my name on the release, based on what I've read about Debian packaging procedures; if that's not right, I can change the name.

Note that these changes are a delta from the RC release; is that the correct thing to do? Or should it be relative to the last stable release (0.6.0)?

The list was based off of this diff: https://github.com/rhempel/ev3dev-lang-python/compare/fb3cdbc...develop

### CODE REVIEW

**Comment by WasabiFan** [comment]
@dlech can you review?

**Comment by dlech** [comment]
It is traditional to give credit by starting a list item with `[<name>]` if it is not the person signing the changelog.

Also make sure to wrap to 80 lines. I didn't count, but one line looked kind of long, especially if you add the author.

**Comment by WasabiFan** [comment]
OK, I'll add that.

**Comment by WasabiFan** [comment]
:new:

**Comment by WasabiFan** [comment]
Can I get a quick review from @dlech on this to confirm that it's properly formatted? If it is, we should be ready for release.

**Comment by dlech** [comment]
LGTM. You can use `lintian` to tell for sure that it is properly formatted.

**Comment by WasabiFan** [comment]
I wasn't able to persuade lintian to do what I wanted with my low level of patience, so I'm going to assume it's fine :laughing: It might be good for whoever actually does the release to run it on the `.deb` that they produce just in case, but even that's probably overkill; even if the changelog isn't perfect, it will still do its job.

I'm going to merge this and draft a GitHub release (but not actually release it). Is there anything else that people want to do before the library is ready?

**Pull request merged**
