### PR TITLE
Document class-scope constants

### LINKED ISSUE #299: Document string constants
It looks like there isn't any documentation on the constants that we define for commands, states, polarities and other string-based properties. What must be changed to make them appear in the rendered docs?

### PR DESCRIPTION
**Pull request by ddemidov**
Closes #299.

The generated documentation: http://ev3dev-lang.readthedocs.io/projects/python-ev3dev/en/issue-229

Motor classes got a lot of constants: http://ev3dev-lang.readthedocs.io/projects/python-ev3dev/en/issue-229/motors.html#tacho-motor

### CODE REVIEW

**Comment by ddemidov** [comment]
Please don't merge yet, there are some platform-specific constants to do.

**Comment by WasabiFan** [comment]
I may be incompetent when reviewing at 5:00, but at 2:00 I think I have a handle on things :grin:

**Comment by ddemidov** [comment]
I believe I am done. One thing I am not sure about is the documentation for Leds class: http://ev3dev-lang.readthedocs.io/projects/python-ev3dev/en/issue-229/other.html#ev3dev.ev3.Leds. It has manually entered lists for EV3 and for BrickPi platforms, and the documentation generator also picked up constants for the EV3 platform.

I don't think we can get auto-documentation for both platforms, so may be its best to leave the manually entered section as is.

**Comment by WasabiFan** [comment]
> may be its best to leave the manually entered section as is.

I'd agree with that. Honestly, if someone can't figure out what a constant named `GREEN` means in an LED class, they aren't going to get far anyway.

**Comment by ddemidov** [comment]
So, remove the autodoc strings, or keep both?

**Comment by WasabiFan** [comment]
I vote to keep the manual stuff as-is, and put documentation everywhere else (i.e. the common bits),

**Comment by ddemidov** [comment]
Ok, I've stripped led-related commits from the PR.

**Pull request merged**
