### PR TITLE
Get rid of size parameter in FileCache.read

### PR DESCRIPTION
**Pull request by ddemidov**
See discussion in 91bfa71551d8a9f6649705fda68de904254ef745.

### CODE REVIEW

**Comment by ddemidov** [comment]
I've split the commit into smaller parts. You may want to pick the first three even if you decide to omit c9b6d35 for now.

**Comment by rhempel** [comment]
Have you tested the code on the target yet :-)

**Comment by ddemidov** [comment]
I've tested in on fake target. Why, do you get any failures?

**Comment by ddemidov** [comment]
Ok, I've just tested it on EV3 and both attribute IO and keyboard work.

**Comment by rhempel** [comment]
Thanks!

**Pull request merged**
