### PR TITLE
Fix names of outputs for BrickPi.

### PR DESCRIPTION
**Pull request by fryfrog**

### CODE REVIEW

**Comment by fryfrog** [comment]
Also, I have no idea how to test this besides the bit of fiddling in IRC that @dlech did with me.

**Comment by dlech** [comment]
I think it's pretty safe to say that this will work. You should also fix the input ports while you are at it.

**Comment by ddemidov** [comment]
Would it be a good idea to move this info into the [platforms section](https://github.com/ev3dev/ev3dev-lang/blob/develop/spec.json#L1460) of the ev3dev/ev3dev-lang specification? Something like 
```json
platforms = {
    "brickpi" : {
        "ports" : {
            "input" : {...},
            "output" : {...}
        }
    }
}
```

**Comment by fryfrog** [comment]
It'll be this evening before I can fire up that Pi3 w/ BrickPi to get the input port names, I can create a second pull request for that.

**Comment by rhempel** [comment]
Merging this PR, thanks! Looking forward to the input port fix.

**Pull request merged**
