### PR TITLE
Removed __EV3_MODULE_connected

### PR DESCRIPTION
**Pull request by antonvh**
I think we agree on these changes, at least

### CODE REVIEW

**Comment by antonvh** [comment]
Is this helpful? It works on my brickpi....

**Comment by rhempel** [comment]
I will look at this tonight and maybe tomorrow - super busy the next couple of days

**Comment by rhempel** [comment]
Anton, did you also make the change in the autogen templates to generate the changes in the bindings? I'm going to do the merge now but I'll also fix up the bindings, OK?

**Comment by rhempel** [comment]
i just pushed a first draft of `autogen`ed `ev3dev.py` with support for helper functions that take kwargs. I still need to clean up how string vs int arguments are handled, but I'm pretty happy with how this worked out - comments on naming etc are welcome!

**Comment by antonvh** [comment]
Nice. You can't have slashes in parameters, though. ("hold_pid/Ki") python thinks you want to divide it then.





I would also make two lists of properties: _int_properties and _str_properties so you can sort them out and cast them in the helper function.

**Comment by rhempel** [comment]
Yes, I caught that - check out what I just pushed - it works pretty well now

**Comment by rhempel** [comment]
I have merged with @ddemidov's more recent pull request - closing this one.

**Pull request closed without merging**
