### PR TITLE
README for EV3D4

### PR DESCRIPTION
**Pull request by dwalton76**
This is for issue #239 

The commits are a little screwed up right now, I'll work on cleaning this up.  I had a commit I had made to the changelog but never did a pull request for it so in an attempt to 'git rebase -i' to drop that commit I screwed something up so that it is now showing 48 commits.

### CODE REVIEW

**Comment by WasabiFan** [comment]
Yeah, looks like you rewrote a fair bit of history :laughing: I suspect that a `git rebase origin/master` would fix the issue. If not, there's always the `git diff > tmp.patch && git reset --hard master && git apply tmp.patch` option. Don't count on my impromptu git-ing there, though.

**Comment by dwalton76** [comment]
https://xkcd.com/1597/

**Comment by WasabiFan** [comment]
Maybe @dlech's 1337 skills can get us out of this mess :laughing:

**Comment by dwalton76** [comment]
Am going with the nuke option...will re-issue this in a second

**Pull request closed without merging**
