### PR TITLE
Update changelog for 0.7.0

### PR DESCRIPTION
**Pull request by dwalton76**

### CODE REVIEW

**Comment by WasabiFan** [comment]
I think the idea is that you add a new entry instead of modifying the previous one.

**Comment by dwalton76** [comment]
0.7.0-rc1 was never released though....0.6.0 is the last entry in master

**Comment by WasabiFan** [comment]
The develop branch was never merged and no one tagged a release on the repo, however the package was released via the ev3dev archives. So that version _was_ released by @dlech, but normal release procedures weren't followed on the repo side (probably because @rhempel was too busy with other things).

**Comment by WasabiFan** [comment]
See #180.

**Comment by dwalton76** [comment]
ah, gotcha.  yeah ignore this pull request :(  I need to read the ev3dev packaging page that David sent me.  Will aim to update the changelog tomorrow evening and hopefully build the package, do the release then.  Sound good?

**Comment by WasabiFan** [comment]
Yep! Sounds good to me.

**Comment by WasabiFan** [comment]
@dwalton76 Any update on this? I'd be happy to update the changelog if you don't have the time, although I won't be able to publish the release.

Once we get this package published, @dlech has said that we should be ready to release a new official ev3dev image (the first one since December of last year) so I'd like to get this done fairly quickly so we aren't holding that up.

**Comment by dwalton76** [comment]
@WasabiFan I haven't had a chance to get to it, if you can do it that would be much appreciated.

**Comment by WasabiFan** [comment]
OK, I should be able to do it within the next few hours. @dlech, who should I mark as the person who did the release? Me because I created the changelog entry, @dwalton76 for the code / preparation, or @dlech for publishing it?

**Pull request closed without merging**
