### PR TITLE
Revert "Fixed input ports"

### PR DESCRIPTION
**Pull request by rhempel**
Reverts rhempel/ev3dev-lang-python#116

### CODE REVIEW

**Comment by rhempel** [comment]
Please resubmit this PR against the `develop` branch

**Comment by ddemidov** [comment]
ping @antonvh

**Comment by dlech** [comment]
I'm actually going to change the BrickPi port names in the next kernel release, so this PR can be dropped.

**Comment by antonvh** [comment]
Will they be the same on all platforms? Great!


Sent with Mixmax

On Thu, Feb 4, 2016 at 7:15 AM David Lechner <notifications@github.com> wrote:
I'm actually going to change the BrickPi port names in the next kernel release,
so this PR can be dropped.

**Comment by dlech** [comment]
Probably not. See ev3dev/ev3dev#524. I'm still not sure what is the best way to handle this.

**Comment by rhempel** [comment]
So we can skip this PR?

**Comment by dlech** [comment]
It doesn't matter. Either way, things will be broken after the next kernel release.

**Comment by rhempel** [comment]
Yes they will - we'll find out how resilient our language infrastructure is after that :-)

**Pull request closed without merging**
