### PR TITLE
Added button class

### PR DESCRIPTION
**Pull request by antonvh**
Please only merge commit where I add the button class

I don't understand why my liquid files are out of sync with yours. At some point git is beyond me. Wouldn't you add me as author?

### CODE REVIEW

**Comment by ddemidov** [comment]
You can sync your repo with @rhempel's by doing this:
```
git checkout -b local # keep local changes in a local branch
git checkout master
git fetch origin
git reset --hard origin/master # this will hard reset your master branch to origin (i assume origin points to @rhempel's repo)
git cherry-pick <commit-from-local-branch> # pick commits from local branch you want to push to main repo
```

**Comment by antonvh** [comment]
Thanks. Git is back in sync now. This is a nice and clean pull request now.

**Comment by ddemidov** [comment]
> Wouldn't you add me as author?

I think when @rhempel said he would add us as authors, he meant [here](https://github.com/rhempel/ev3dev-lang-python/blob/c07900d37e542443d03d2b2d8a7bd603c15423b4/setup.py#L7). Anyway, doing pull requests has an advantage of mandatory code review, so I would stick with those even if we are given push permissions.

**Comment by antonvh** [comment]
Sure. Let's be careful to agree on who does what so pull requests don't collide. 

The advantage of push rights is seeing what the others are doing faster, and the ability to rebase and keep the tree clean.

**Comment by ddemidov** [comment]
Also, you can press `watch` button at the top of the repo page (and recieve email notifications when somebody pushes something or comments on an issue).

**Comment by rhempel** [comment]
I will get to this over the weekend, I think - just installed pycharm and I now understand better what we want to do with hinting and so on.

**Comment by rhempel** [comment]
I have fixed up the templates to remove whitespace, and cleaned up the driver name list template. For buttons, we need to do something similar to the LEDs  - which is to create a generic class for Button, and platform specific instances for each button.
Also, @topikachu's button class implementation does not cache the file descriptor for the `ioctl` calls - and I'd like the generic driver to be able to handle that.
I'm trying to get this fixed up this morning, but life might get in the way :-)

**Pull request closed without merging**
