### PR TITLE
Update demo files to use address instead of port_name

### PR DESCRIPTION
**Pull request by ddemidov**

### CODE REVIEW

**Comment by rhempel** [comment]
@ddemidov, I managed to forget that I had a `develop` and `master` branch in my repo - please verify that the `master` branch in this repo is up to date with your device enumeration and other changes.

**Comment by ddemidov** [comment]
I don't have ev3 around now, but [`git diff master..develop`](https://github.com/rhempel/ev3dev-lang-python/compare/develop) shows that the branches are not in sync.

**Comment by rhempel** [comment]
No, they are not in sync - master got ahead of develop and develop got some unmergeable changes. the `master` branch should be the reference at this point  I just wanted to make sure that your work on the device enumeration was still good.

**Comment by ddemidov** [comment]
Ok, I'll check this tonight (in about 6 hours).

**Comment by rhempel** [comment]
Thks, I am at work also :-) You have a young family to help look after when work is done.

**Comment by ddemidov** [comment]
The master branch looks ok (and the demos work).

**Comment by rhempel** [comment]
Thks! I'll tag 0.6.0 later this afternoon - and get develop in sync with master

**Pull request merged**
