### PR TITLE
Update to the ev3dev-lang branch with tacho support

### PR DESCRIPTION
**Pull request by rhempel**
- New motor instantiation code for linear motors
- Add new motor parameter and motion unit tests
- Eliminate speed_regulation_enabled attribute
- Rename speed_regulation_[pid] to speed_[pid]
- Remove API test for speed_regulation_enabled

### CODE REVIEW

**Comment by ddemidov** [comment]
> Eliminate speed_regulation_enabled attribute
Rename speed_regulation_[pid] to speed_[pid]

These are just the matter of updating spec and rerunning autogen script, right?

**Comment by rhempel** [comment]
Yes, I've updated the spec and will be pushing a change here shortly

**Comment by ddemidov** [comment]
Looks good to me. Btw, does github sends notifications when someone adds a reaction to a PR?

**Comment by rhempel** [comment]
Yes, I get emails to all PRs that I submit, or on repos that I own

**Comment by ddemidov** [comment]
I was talking about the [new feature](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments) github pushed recently :).

**Comment by rhempel** [comment]
Yes, I see that thumbs up :-) I want to squash some of the last few commits I did on `develop` - there are no outstanding PRs, so I think it's OK. I made a mess of some merges last week

**Comment by rhempel** [comment]
I did a merge on the command line and pushed to develop - had to rebase to clean up commit history - no more development directly on `develop` for me :-)

**Pull request closed without merging**
